### PR TITLE
Don't request animation frames when we don't need them

### PR DESCRIPTION
**Pull request by mpeterson2**
This library caused a pretty big idle performance hit with the CPU usage around ~30-50% even when no animations were running. This was due to requesting the animation frame even though nothing was playing. With this PR, animation frames will only be requested when required and it now idles at 0% CPU.

### CODE REVIEW

**Comment by bodymovin** [comment]
Thanks! It sounds like a good idea, I'll look into it. 
I need to make some adjustments first.
But 50% CPU usage for that idle state doesn't seem correct. Are you sure you measured it correctly?

**Comment by mpeterson2** [comment]
Honestly didn't measure too much. Just noticed a large amount of CPU usage due to this.

**Comment by bodymovin** [comment]
done on commit "8c3dae2f242b9a90f641d6cdb77795d76bd52de6"  
thanks for the suggestion and the PR!

**Comment by mpeterson2** [comment]
Awesome, thank you!

**Pull request closed without merging**
