### PR TITLE
replace window with global window

### PR DESCRIPTION
**Pull request by ionutcirja**

### CODE REVIEW

**Comment by sebryu** [comment]
I would be happy if this will be merged soon 👍 Good job @ionutcirja

**Comment by sebryu** [comment]
Oh, I have tried to deploy your version, but now I get:
```
       ReferenceError: navigator is not defined
           at /app/node_modules/bodymovin/build/player/bodymovin.js:4:54
```

**Comment by mettin** [comment]
any plans to merge this?

**Comment by sebryu** [comment]
@mettin I have managed to get this work (without these changes) on server with requiring the package only in code not accessible by server, like this:
```
if (!isServer) {
const loadAnimation = require('bodymovin/build/player/bodymovin').loadAnimation;
...
}
```

**Comment by mettin** [comment]
thanks @sebryu. A lot better!

**Pull request closed without merging**
